export const CHANGE_PAGE = 'CHANGE_PAGE';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_JOURNEYS = 'FETCH_JOURNEYS';
export const CREATE_JOURNEY = 'CREATE_JOURNEY';
export const DELETE_JOURNEY = 'DELETE_JOURNEY';
export const END_JOURNEY = 'END_JOURNEY';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
